In [11]:
import pandas as pd
import numpy as np

In [2]:
results = pd.read_pickle('../datasets/epic-100/esvs/f_train_mf-esv-min_frames=1-max_frames=8.pkl')
labels = pd.read_pickle('../datasets/epic-100/features/67217_train_features.pkl')

In [3]:
l = labels['labels']

In [8]:
idx = 'P01_01_10'

alie = build_dict(l)

In [5]:
def build_dict(lst):
    return {d['narration_id']: d for d in lst}

In [9]:
alie[idx]

{'narration_id': 'P01_01_10',
 'participant_id': 'P01',
 'video_id': 'P01_01',
 'narration_timestamp': '00:00:23.340',
 'start_timestamp': '00:00:24.97',
 'stop_timestamp': '00:00:26.20',
 'start_frame': tensor([1498]),
 'stop_frame': tensor([1572]),
 'narration': 'open drawer',
 'verb': 'open',
 'verb_class': tensor([3]),
 'noun': 'drawer',
 'noun_class': tensor([8]),
 'all_nouns': ('drawer',),
 'all_noun_classes': tensor([8]),
 'frame_size': tensor([256]),
 'num_frames': tensor([75])}

In [10]:
n_frames = 3

In [62]:
total=alie[idx]['num_frames']
bins = np.linspace(0,total,11,dtype=int,axis=0).squeeze()

# data=np.random.random(100)
# np.digitize(data,bins)
# np.median(bins,axis=1)

median = (0.5*(bins[1:]+bins[:-1])).astype(int)
median

array([ 3, 11, 18, 26, 33, 41, 48, 56, 63, 71])

In [38]:
wtf = results['uids']

In [41]:
pff = [seq_idxs[3] for seq_idxs in results['sequence_idxs']]

In [63]:
[median[idx] for idx in pff]

[array([41]),
 array([18, 56]),
 array([11, 41, 63]),
 array([11, 26, 48, 63]),
 array([11, 26, 41, 56, 71]),
 array([ 3, 18, 33, 41, 56, 71]),
 array([ 3, 18, 26, 41, 48, 56, 71]),
 array([ 3, 11, 26, 33, 41, 48, 63, 71])]

In [65]:
from pathlib import Path

In [67]:
path = Path('../datasets/epic-100/esvs/f_train_mf-esv-min_frames=1-max_frames=8.pkl')

In [71]:
'val' in path.name

False

In [79]:
path.resolve()

PosixPath('/mnt/storage/scratch/jb18789/datasets/epic-100/esvs/f_train_mf-esv-min_frames=1-max_frames=8.pkl')

In [80]:
xd = np.array()

TypeError: array() missing required argument 'object' (pos 1)

In [81]:
mtrn_verb = np.array([
    [35.53,26.51,81.80,72.21,29.38,11.87,59.11,31.17],
    [39.42,28.87,84.29,72.84,33.15,13.10,63.84,32.75],
    [41.88,30.66,85.67,73.91,35.38,13.68,67.17,33.59],
    [43.94,30.93,86.78,73.87,37.22,13.58,69.31,33.33],
    [45.91,31.81,87.66,74.04,38.55,14.17,70.58,33.83],
    [46.97,31.67,88.18,74.02,39.76,14.18,71.98,33.47],
    [47.98,32.10,88.95,74.18,40.54,14.38,72.90,34.49],
    [48.51,32.07,89.00,74.15,41.24,13.85,73.73,33.96]
])

mf_verb = np.array([
    [80.50,65.99,96.54,89.92,79.23,56.22,94.17,79.73],
    [81.94,66.64,97.12,90.08,81.20,57.09,95.36,80.34],
    [82.81,67.02,97.51,90.52,82.16,57.35,95.84,80.23],
    [83.33,67.02,97.74,90.35,82.91,57.51,96.07,80.69],
    [83.91,66.89,97.86,90.25,83.39,57.44,96.56,80.73],
    [84.28,67.00,97.96,90.34,84.00,57.60,96.68,80.44],
    [84.67,67.10,98.21,90.37,84.33,57.51,96.83,80.31],
    [84.98,66.90,98.36,90.34,84.60,57.75,97.04,80.85]
])


In [91]:
np.array([mf_verb.min(axis=0),
      mf_verb.max(axis=0)])

array([[80.5 , 65.99, 96.54, 89.92, 79.23, 56.22, 94.17, 79.73],
       [84.98, 67.1 , 98.36, 90.52, 84.6 , 57.75, 97.04, 80.85]])

In [85]:
mf_verb.max(axis=0)

array([84.98, 67.1 , 98.36, 90.52, 84.6 , 57.75, 97.04, 80.85])

In [87]:
mf_verb

array([[80.5 , 65.99, 96.54, 89.92, 79.23, 56.22, 94.17, 79.73],
       [81.94, 66.64, 97.12, 90.08, 81.2 , 57.09, 95.36, 80.34],
       [82.81, 67.02, 97.51, 90.52, 82.16, 57.35, 95.84, 80.23],
       [83.33, 67.02, 97.74, 90.35, 82.91, 57.51, 96.07, 80.69],
       [83.91, 66.89, 97.86, 90.25, 83.39, 57.44, 96.56, 80.73],
       [84.28, 67.  , 97.96, 90.34, 84.  , 57.6 , 96.68, 80.44],
       [84.67, 67.1 , 98.21, 90.37, 84.33, 57.51, 96.83, 80.31],
       [84.98, 66.9 , 98.36, 90.34, 84.6 , 57.75, 97.04, 80.85]])